# Generated by Django 5.0.6 on 2024-06-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'admin_table',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.CharField(choices=[('CSE(R)', 'CSE(Regular)'), ('CSE(H)', 'CSE(Honors)'), ('CSIT', 'CS&IT')], max_length=100)),
                ('program', models.CharField(choices=[('B.TECH', 'Bachelor of Technology'), ('M.TECH', 'Masters of Technology'), ('MBA', 'Master of Business Administration')], max_length=50)),
                ('academicyear', models.CharField(choices=[('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024')], max_length=20)),
                ('semester', models.CharField(choices=[('ODD', 'ODD'), ('EVEN', 'EVEN')], max_length=10)),
                ('year', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('coursecode', models.CharField(max_length=20)),
                ('coursetitle', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'course_table',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('facultyid', models.BigIntegerField(unique=True)),
                ('fullname', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHERS', 'OTHERS')], max_length=20)),
                ('department', models.CharField(choices=[('CSE(R)', 'CSE(Regular)'), ('CSE(H)', 'CSE(Honors)'), ('CSIT', 'CS&IT')], max_length=50)),
                ('qualification', models.CharField(choices=[('B.TECH', 'Bachelor of Technology'), ('M.TECH', 'Masters of Technology'), ('Ph.D', 'Doctor of Philosophy')], max_length=50)),
                ('designation', models.CharField(choices=[('Prof', 'Professor'), ('Assoc.Prof', 'Associate Professor'), ('Asst.Prof', 'Assistant Professor')], max_length=50)),
                ('password', models.CharField(default='klu123', max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('contact', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'faculty_table',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('studentid', models.BigIntegerField(unique=True)),
                ('fullname', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHERS', 'OTHERS')], max_length=20)),
                ('department', models.CharField(choices=[('CSE(R)', 'CSE(Regular)'), ('CSE(H)', 'CSE(Honors)'), ('CSIT', 'CS&IT')], max_length=50)),
                ('program', models.CharField(choices=[('B.TECH', 'Bachelor of Technology'), ('M.TECH', 'Masters of Technology'), ('MBA', 'Master of Business Administration')], max_length=50)),
                ('semester', models.CharField(choices=[('ODD', 'ODD'), ('EVEN', 'EVEN')], max_length=10)),
                ('year', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('password', models.CharField(default='klu123', max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('contact', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'student_table',
            },
        ),
    ]
