# Generated by Django 5.0.6 on 2024-06-14 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_course_credits_course_ltps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='credits',
        ),
        migrations.RemoveField(
            model_name='course',
            name='ltps',
        ),
    ]
